site_name: UCTIRJ - Informes

nav:
    - Home: 'index.md'
    - Por que se organizar?: 'informe03.md'
    - Indice de correção monetária do FGTS e a atuação do SINDPDRJ: 'informe02.md'
    - 1º de maio e os profissionais de TI: 'informe01.md'
    
    
theme:
  name: material #para usar esse tema é preciso instalar o mkdocs-material
  logo: assets/logo.png
  favicon: assets/logo.png
  language: pt-br
  palette:
    - scheme: default
      primary: red
      toggle:        
        icon: material/weather-night
        name: Modo noturno
    - scheme: slate 
      primary: deep purple
      toggle:
        icon: material/weather-sunny
        name: Modo claro
extra:
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/uc_cbti_rj
      name: uctirj no twitter
    - icon: fontawesome/brands/github
      link: https://github.com/cbti-rj
      name: uctirj no github
  

markdown_extensions: #para usar esse tema é preciso instalar o pymdown-extensions
  - pymdownx.tasklist #extende a opção de lista de tarefas
  - pymdownx.mark #extende a opção de marcação
  - pymdownx.tilde #extende a opção de tachado
  - pymdownx.superfences #extende a opção de mostrar código
